### ISSUE TITLE
AttributeError: module 'main' has no attribute 'main'

### ISSUE THREAD

**Issue by mindtheflo** [Planetary-Computers/autotab-starter#13]
After following Quickstart guide, here is what I get trying to run autotab record. 

```
autotab record
Traceback (most recent call last):
  File "/usr/local/bin/autotab", line 33, in <module>
    sys.exit(load_entry_point('autotab', 'console_scripts', 'autotab')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/autotab", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 204, in load
    return functools.reduce(getattr, attrs, module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'main' has no attribute 'main'
```

**Comment by jonasalexander** [comment]
Hi @parisetflorian are you using poetry to manage your virtualenv? If so, I think that might be causing the issue - mind trying `python3 -m venv .venv` for the virtualenv with the most recent version on main?

**Comment by jonasalexander** [comment]
@parisetflorian closing this for now; if you're still having issues feel free to follow up here or in our Discord! https://discord.gg/seGGxSUgzM

**Comment by mindtheflo** [comment]
@jonasalexander Sorry, I missed the notification. I still have the same issue.
I'm not using a virtual environment. I guess that's why python3 -m venv .venv returns nothing.
