### ISSUE TITLE
Running autotab record throws python error

### ISSUE THREAD

**Issue by msfeldstein** [Planetary-Computers/autotab-starter#2]
I went through the quickstart steps, and when i run `autotab record` (in my venv) i get the following error

```
autotab record
Traceback (most recent call last):
  File "/Users/michaelfeldstein/Source/autotab-starter/autotab-env/bin/autotab", line 5, in <module>
    from main import main
ModuleNotFoundError: No module named 'main'
```

MacOS 14.0
Python 3.11.5

**Comment by aelous** [comment]
+1
autotab record

Traceback (most recent call last):
  File "/opt/homebrew/bin/autotab", line 33, in <module>
    sys.exit(load_entry_point('autotab', 'console_scripts', 'autotab')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/bin/autotab", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 204, in load
    return functools.reduce(getattr, attrs, module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'main' has no attribute 'main'

**Comment by miranyx** [comment]
+1

**Comment by miranyx** [comment]
I had to run `pip3 install -e .` manually then it worked without `make install`

**Comment by msfeldstein** [comment]
no dice running `pip install -e .` or `pip3 install -e .`

**Comment by jonasalexander** [comment]
I tried to reproduce on a new Ubuntu machine in the cloud and upgraded my Macbook to MacOS 14 but wasn't able to reproduce with Python 3.10 or 3.11. Just merged a change based on @benni347 's suggestion (thanks for that!) - let me know if that fixes it! @msfeldstein @aelous

**Comment by jonasalexander** [comment]
Hi @msfeldstein @aelous try with the most recent version on main, we fixed a bunch of things. If the issue persists, feel free to join our Discord & I can help debug. https://discord.com/invite/seGGxSUgzM
