### ISSUE TITLE
https://www.autotab.com/dashboard doesnt work 

### ISSUE THREAD

**Issue by devinschumacher** [Planetary-Computers/autotab-starter#32]
<img width="1512" alt="Screenshot 2024-01-14 at 14 09 10" src="https://github.com/Planetary-Computers/autotab-starter/assets/45643901/ad4889cb-32d9-41a0-a600-9988e217650b">

**Comment by alexi** [comment]
Thanks for trying Autotab out, you may have missed our ReadMe:

Thanks for trying out autotab! Over the last few weeks we’ve learned from so many of you and are excited to start rolling out a smoother and more user-friendly autotab V1 (no dependencies!).

As we transition, this repo will no longer be supported. The good news is that any Python code you’ve generated with autotab will of course work as usual.

Join our [Discord channel](https://discord.gg/seGGxSUgzM) to follow along and for a chance to be one of the first to try out new updates!
