### ISSUE TITLE
Docker + Browserless ? 

### ISSUE THREAD

**Issue by accforgithubtest** [Planetary-Computers/autotab-starter#8]
Hello there, this project is a very neat idea and i think has great potential for automating tasks, beyond testing too !

Any plans for containerizing this and using and embedded (container) browser or browserless or etc ?
Browserless might even add the benefit of abstracting away multiple browser support for you ?

For repeatable testing, a container based solution would be a necessity and using the generated files to performing the actions will be a easy way to get the most out of repeatability and scalability. Also removes complexities related to users individual set-up

**Comment by jonasalexander** [comment]
Yes, this is definitely one of the things we're excited to work on soon! Do you mean running it containerized locally or in the cloud/at scale? For the latter you could do something like `autotab play --remote`, wdyt?

**Comment by accforgithubtest** [comment]
Personally, I would love to be able to do this in a way where no data leaves the local network. 
But give the LLM features, you might have to figure out a strategy to either BYO LLM with a compatible API, or provide a openai key to integrate with chat gpt. 

I do not know if / what the monetization plan for this project is - but one question that comes to mind now is will this project ever be fully self-hostable without needing a api key / login into cloud service (assuming a user hosted LLM) ?

**Comment by jonasalexander** [comment]
We are likely to provide an option where you can bring your own Open AI API key. I'm not sure the entire system will be self-hostable. There are already a few things we do around the LLM API calls that I don't think we'll open source and I expect those types of things to grow as we build systems around the LLM to improve accuracy.
